version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ap_user
      POSTGRES_PASSWORD: ap_pass
      POSTGRES_DB: ap_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    restart: unless-stopped

  activepieces:
    image: activepieces/activepieces:latest
    ports:
      - "8080:80"  # غيّر المنفذ هنا حسب ما تسمح به Northflank
    environment:
      AP_ENVIRONMENT: prod
      AP_FRONTEND_URL: https://<اسم_مشروعك>.northflank.app
      AP_DB_TYPE: POSTGRES
      AP_QUEUE_MODE: REDIS
      AP_POSTGRES_HOST: postgres
      AP_POSTGRES_PORT: 5432
      AP_POSTGRES_USERNAME: ap_user
      AP_POSTGRES_PASSWORD: ap_pass
      AP_POSTGRES_DATABASE: ap_db
      AP_REDIS_HOST: redis
      AP_REDIS_PORT: 6379
      AP_ENCRYPTION_KEY: this_is_a_strong_encryption_key
      AP_JWT_SECRET: this_is_a_strong_jwt_secret
    depends_on:
      - postgres
      - redis
    volumes:
      - ./cache:/usr/src/app/cache
    restart: unless-stopped

volumes:
  pgdata:
